version: "3"
services:
  backend:
    container_name: backend 
    build:
        context: ./backend
    depends_on:
      - db  
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    # environment:  
    #   - MONGO_URL=mongodb://db:27017/wallet-api
    #   - PORT=3525
    ports: ['3525:3525'] 

  db:
    container_name: db
    image: mongo:6.0.4
    restart: always
    ports:
      - "27017:27017"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    # environment:  
    #   - BACKEND_URL=http://localhost/api/wallets
